### PR TITLE
fixed wrong entries deleted in case of conflict

### LINKED ISSUE #168: Wrong entries deleted in case of conflict
While testing I noticed that "uniquekeynewidtomaintain" is always read as false regardless what value you set it to.

### PR DESCRIPTION
**Pull request by t-schroeder**
Fixes #168

### CODE REVIEW

**Comment by jpahullo** [comment]
Thanks! Good job!

**Comment by jpahullo** [comment]
I cannot accept the MR from the phone directly. But this job must be accepted. Thanks again!

**Comment by jpahullo** [comment]
Could you review the pgsql version in the .travis-ci.yml to make it pass the CI? Please? Thanks!

**Comment by t-schroeder** [comment]
I raised the postgresql version to 9.5 for moodle's master branch. Hopefully that fixes the travis.ci build.

**Comment by jpahullo** [comment]
All checks passed.

**Pull request merged**
