### PR TITLE
issue #83 - removed option 'both' for compound indexes and left only 'us...

### PR DESCRIPTION
**Pull request by jpahullo**
...erfield' key for all user-related column names.

### CODE REVIEW

**Comment by ndunand** [comment]
Jordi, should we release a new version to the Moodle plugins database?

**Comment by jpahullo** [comment]
I think we could accept those pending PR, and then go ahead.

**Comment by jpahullo** [comment]
If you want to upgrade the plugin version, we could just upgrade a minor version, since I think we do not provide any new feature since the last release, don't we?

**Comment by ndunand** [comment]
Agreed; I just merged all pending PRs (which you had reviewed). So should I increase `$plugin->release = '1.10 (Build: 2014071621)'` to `$plugin->release = '1.11 (Build: 2014071621)'` ? Or do you think `1.10.1` would be more suitable?

**Comment by ndunand** [comment]
And indeed the modifications since 1.10 were all bug fixes (and adding/fixing support for MadiaDB, MSSQL), so no real new features here.

**Comment by jpahullo** [comment]
This is why I think we could do just a minor version, up to something like `1.10.1 (Build: 2015022010)`. What do you think about?

**Comment by ndunand** [comment]
Alright, I'll just do that and release the new plugin to moodle.org 😊

**Comment by jpahullo** [comment]
Please... wait a minute, there is a last issue about compound indexes that we should afford before.

**Comment by jpahullo** [comment]
I'll do a PR in a few minutes.

**Comment by ndunand** [comment]
right... OK 😊

**Pull request merged**
