### PR TITLE
Bug fixes and unit tests

### PR DESCRIPTION
**Pull request by andrewhancox**
Hi,
I am currently using this plugin on a project and have written some unit tests and bug fixes. I hope they are of use.

### CODE REVIEW

**Comment by ndunand** [comment]
Hi Andrew,

Thanks a lot for sharing this.

1. I'm OK with e3ce38e.
2. Can you explain in a nutshell how 8710353 works?
3. In 5634ecf, is this really correct? And if so, can't we then simply replace `WHERE quiz IN ($idsstr) AND quiz=q.id` with `WHERE  quiz=q.id`?

**Comment by andrewhancox** [comment]
Nicolas,
2. The update grades method gets a list of all the gradeitems which correspond to an activity that has been affected by the merging of the users, it then forces an update of the user's grade for the activity and so (if necessary) the course. Without forcing this to happen here it will not occur until the gradebook entry is manually modified.
3. You're correct, I have simplified that query.

**Comment by andrewhancox** [comment]
@ndunand I have just pushed a couple of changes - a requireonce to load a file that can, in some situations be missing and a requireonce to fix an edge case when rendering the settings.

**Comment by jpahullo** [comment]
Hi all!

I see your contribution. Thank you very much @andrewhancox !!! We needed unit testing, and you finally added them!

I have taken a close look of the code and it seems ok. I agree with  @ndunand on this. I also knew that issue regarding to capabilities (having moodle/site:config capability but not mergeusers and viceversa). Thank you.

I will try this version in our development instance of Moodle at our University. With "real" data I can check if the behaviour is correct at the end.

Good job @andrewhancox! Good job @ndunand!

Jordi

**Comment by ndunand** [comment]
@andrewhancox thanks again for sharing this, I ran it without problems on my test server, so I think it's good to go.
@jpahullo thanks for your input about the code, I'll trust your judgement on this.

**Pull request merged**
