### PR TITLE
issue #86 - adding compound index for 'assign_grades'.

### PR DESCRIPTION
**Pull request by jpahullo**

### CODE REVIEW

**Comment by ndunand** [comment]
Great, thanks!

**Comment by jpahullo** [comment]
You're welcome!

I think we could push a new release to moodle.org, don't you think?

Thanks a lot!

**Comment by ndunand** [comment]
Yes, I'll to that in a few minutes.

**Comment by jpahullo** [comment]
Excellent! What a team we are!

**Pull request merged**
