### PR TITLE
#193 - Allow automatic Moodle Plugins release when defining git tag

### PR DESCRIPTION
**Pull request by jpahullo**

### CODE REVIEW

**Comment by jpahullo** [comment]
Hi @ndunand!

Could you please review this PR?

I push the changes for automatic release of new git tags into Moodle Plugins directory.

Also, since that requires a new file CHANGES.md, I decided to split the current content of README.md into two parts: One stable on README.md and then the other one, variable from git tag to git tag, into CHANGES.md.

Also, since this version of the plugin has some PHP requirements, I bump up the minimum Moodle version up to 3.9 as you suggested in one post.

Let me hear you soon ;-)

Thanks a lot in advance!

**Comment by jpahullo** [comment]
By the way, since our git tags have the form YYYYMMDD, I modified the github workflow to only push tags starting from `2`. This way we can keep the same way now on too. So, if we need other kind of git tags not be published on the Moodle Plugins directory, we only need to start with a different first character.

Thanks!

**Comment by ndunand** [comment]
Hi @jpahullo ,

Great, all good for me. I'll merge this and let you try the workflow by adding a new tag 😊 . The moodle.org WS token has been set by me so it should work.

**Comment by jpahullo** [comment]
Hi @ndunand! It worked!!! 

* New release: https://moodle.org/plugins/tool_mergeusers/versions
* Workflow run in very few seconds. Fantastic!

**Comment by ndunand** [comment]
Great @jpahullo 😊 

Thanks for the hint, I already deployed this on many other plugins.

**Comment by jpahullo** [comment]
Oh really? It's fantastic and super-easy. I'll use it too for the other plugins we have at work and they are on the Plugins Directory.

Big hugs!

**Pull request merged**
