### PR TITLE
issue #152 - lib/mergeusertool.php: support any Moodle DB

### PR DESCRIPTION
**Pull request by jpahullo**
Nice to have a PR removing more lines than adding them.

### CODE REVIEW

**Comment by jpahullo** [comment]
Finally I updated properly the .travis.yml to execute the whole pipeline both in pgsql and mysql. Now I have to deal with these checks:

```
There was 1 error:
1) tool_mergeusers_quiz_testcase::test_mergeconflictingquizattempts
Unexpected debugging() call detected.
Debugging: Did you remember to make the first column something unique in your call to get_records? Duplicate value '367000' found in column 'iteminstance'.
* line 1254 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
* line 464 of /admin/tool/mergeusers/lib/mergeusertool.php: call to mysqli_native_moodle_database->get_records_sql()
* line 276 of /admin/tool/mergeusers/lib/mergeusertool.php: call to MergeUserTool->updateGrades()
* line 197 of /admin/tool/mergeusers/lib/mergeusertool.php: call to MergeUserTool->_merge()
* line 181 of /admin/tool/mergeusers/tests/quiz_test.php: call to MergeUserTool->merge()
* line ? of unknownfile: call to tool_mergeusers_quiz_testcase->test_mergeconflictingquizattempts()
* line 1071 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
* line 939 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit\Framework\TestCase->runBare()
* line 698 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 894 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestResult->run()
* line 755 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestCase->run()
* line 755 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
* line 545 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit\Framework\TestSuite->run()
* line 195 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\TestRunner->doRun()
* line 148 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\Command->run()
* line 53 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit\TextUI\Command::main()
/home/travis/build/moodle/lib/phpunit/classes/advanced_testcase.php:88
To re-run:
 vendor/bin/phpunit --configuration "tool_mergeusers_quiz_testcase" admin/tool/mergeusers/tests/quiz_test.php
--
There was 1 failure:
1) tool_mergeusers_assign_testcase::test_mergenonconflictingassigngrades
Failed asserting that false matches expected true.
/home/travis/build/moodle/admin/tool/mergeusers/tests/assign_test.php:74
/home/travis/build/moodle/lib/phpunit/classes/advanced_testcase.php:80
To re-run:
 vendor/bin/phpunit --configuration "tool_mergeusers_assign_testcase" admin/tool/mergeusers/tests/assign_test.php
ERRORS!
Tests: 8, Assertions: 33, Errors: 1, Failures: 1.
```

**Comment by jpahullo** [comment]
@ndunand, could you revisit this PR? If so, please, if you consider it is ok, go ahead and accept the PR.

Thank you so much!

Jordi

**Comment by jpahullo** [comment]
ups...  I saw I left the string `errordatabase` which will never be used again. Apart from this, something else?

Thanks!

**Comment by jpahullo** [comment]
Done, removed unused string.

**Comment by jpahullo** [comment]
@ndunand, shall we accept this MR?

**Comment by ndunand** [comment]
@jpahullo thanks for this ! Sorry I couldn't keep up with your speed.

Great job, as always

**Pull request merged**
